sudo: required
language: generic
services:
  - docker

env:
  global:
   - SHA=$(git rev-parse HEAD)
   - CLOUDSDK_CORE_DISABLE_PROMPTS=1

before_install:
## this downloads the google cloud sdk and install it locally on the instance assigned to us by travis ci

  - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  ## above is for generating service-account.json as encrypted

  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project multi-k8s-258404
  - gcloud config set compute/zone us-central1-a	
  - gcloud container clusters get-credentials multi-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "DOCKER_USERNAME" --password-stdin 
  - docker build -t drumster88/react-test -f ./client/Dockerfile.dev ./client 

script:
  - docker run -e CI=true drumster88/react-test npm run test -- --coverage
 
deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master 