apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-persistent-volume-claim
spec:
## if we attach this claim to a pod, K8s must find an instance of storage that
# meets the below requirements:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi    